# Generated by Django 5.0.2 on 2024-04-13 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_plan_is_primary'),
        ('student_admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='adminuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='user_permissions',
        ),
        migrations.AddField(
            model_name='studentuser',
            name='plan_a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_plans_a', to='plans.plan'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='plan_b',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_plans_b', to='plans.plan'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='plan_c',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_plans_c', to='plans.plan'),
        ),
    ]
