# Generated by Django 5.0.2 on 2024-04-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_alter_plan_name'),
        ('student_admin', '0002_remove_adminuser_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='plan_a',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='plan_b',
        ),
        migrations.RemoveField(
            model_name='studentuser',
            name='plan_c',
        ),
        migrations.AddField(
            model_name='studentuser',
            name='plans',
            field=models.ManyToManyField(to='plans.plan'),
        ),
    ]
