# Generated by Django 5.0.2 on 2024-04-13 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_alter_plan_name'),
        ('student_admin', '0003_remove_studentuser_plan_a_remove_studentuser_plan_b_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentuser',
            name='plans',
        ),
        migrations.AddField(
            model_name='studentuser',
            name='plan_a',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='A', to='plans.plan'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='plan_b',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='B', to='plans.plan'),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='plan_c',
            field=models.OneToOneField(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='C', to='plans.plan'),
        ),
    ]
