# Generated by Django 4.2.10 on 2024-04-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_admin', '0005_remove_studentuser_plan_a_remove_studentuser_plan_b_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='cohort',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
