# Generated by Django 4.1.7 on 2024-04-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_admin', '0006_studentuser_cohort'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='total_credits_in_plan',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='total_credits_taken',
            field=models.FloatField(default=0),
        ),
    ]
