# Generated by Django 5.0.2 on 2024-04-19 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0011_rename_courses_plan_course_dictionary_and_more'),
        ('student_admin', '0007_remove_studentuser_plans_studentuser_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentuser',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='plans.plan'),
        ),
    ]
