# Generated by Django 5.0.2 on 2024-04-19 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_admin', '0008_alter_studentuser_plan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentuser',
            old_name='plan',
            new_name='plans',
        ),
    ]
