# Generated by Django 5.0.4 on 2024-04-22 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_admin', '0008_studentuser_courses_taken'),
        ('student_admin', '0010_remove_studentuser_plans_studentuser_plans'),
    ]

    operations = [
    ]
