# Generated by Django 4.1.7 on 2024-04-22 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_admin', '0009_remove_studentuser_total_credits_in_plan_and_more'),
        ('student_admin', '0010_remove_studentuser_plans_studentuser_plans'),
    ]

    operations = [
    ]
