# Generated by Django 5.0.4 on 2024-04-22 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_admin', '0011_merge_20240422_0008'),
        ('student_admin', '0011_merge_20240422_1407'),
    ]

    operations = [
    ]
