# Generated by Django 4.1.7 on 2024-04-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_admin', '0012_merge_20240422_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentuser',
            name='majorII_credits',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='majorI_credits',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='minorII_credits',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='studentuser',
            name='minorI_credits',
            field=models.FloatField(default=0),
        ),
    ]
