# Generated by Django 4.1.7 on 2024-04-12 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_rename_prerequistes_course_prerequistes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='prerequistes',
            new_name='prerequisites',
        ),
    ]
