# Generated by Django 4.1.7 on 2024-04-13 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rename_prerequistes_course_prerequisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='corequisite',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='course',
            name='satisfies',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='time_offered',
            field=models.TextField(default=None),
        ),
    ]
