# Generated by Django 4.1.7 on 2024-04-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_corequisite_alter_course_satisfies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=10)),
            ],
        ),
    ]
