# Generated by Django 4.1.7 on 2024-04-14 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_selectedcourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SelectedCourse',
        ),
    ]
