# Generated by Django 4.1.7 on 2024-04-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_course_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='satisfies',
            field=models.JSONField(default=dict),
        ),
    ]
