# Generated by Django 5.0.2 on 2024-04-10 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='course_selected',
        ),
        migrations.AddField(
            model_name='plan',
            name='courses',
            field=models.JSONField(default=dict),
        ),
    ]
