# Generated by Django 5.0.2 on 2024-04-12 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('plans', '0002_remove_plan_course_selected_plan_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='plan',
            field=models.ManyToManyField(to='courses.course'),
        ),
    ]
