# Generated by Django 5.0.2 on 2024-04-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0003_plan_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='is_primary',
            field=models.BooleanField(default=False),
        ),
    ]
