# Generated by Django 5.0.2 on 2024-04-13 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0004_plan_is_primary'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='name',
            field=models.CharField(default='A', max_length=1),
        ),
    ]
