# Generated by Django 5.0.2 on 2024-04-13 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0005_plan_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='plan',
        ),
    ]
