# Generated by Django 5.0.2 on 2024-04-13 05:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0007_alter_plan_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='student',
            field=models.ManyToManyField(related_name='plans', to=settings.AUTH_USER_MODEL),
        ),
    ]
