# Generated by Django 5.0.2 on 2024-04-13 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0009_remove_plan_student_plan_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='student',
        ),
    ]
