# Generated by Django 5.0.2 on 2024-04-19 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0012_studentcounts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentCounts',
        ),
    ]
