# Generated by Django 5.0.2 on 2024-04-25 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0014_counts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counts',
            name='semester',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='counts',
            name='year',
            field=models.CharField(max_length=4),
        ),
    ]
