# Generated by Django 5.0.2 on 2024-04-25 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0016_remove_plan_is_primary_plan_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='primary',
        ),
    ]
